#!/usr/bin/env python

'''
This script searches for the definition of a word
specified on the command line on vocabulary.com
'''

import argparse
from urllib2 import urlopen
from bs4 import BeautifulSoup

def parseArguments():
    parser = argparse.ArgumentParser()
    parser.add_argument( "word", help="Word for which the definition is to be searched" )
    args = parser.parse_args()
    return args.word

# TODO: Add an option to show synonyms
# TODO: Add an option to show usage
# TODO: Add an option to show only a particular part of speech
# TODO: Add an option to show the detailed definition
# TODO: Write tests
def main():
    wordToSearch = parseArguments()
    baseUrl = "https://www.vocabulary.com/dictionary/"
    url = baseUrl + wordToSearch
    soup = BeautifulSoup( urlopen( url ), "html.parser" )
    # We'll find all the definitions in h3 elements
    h3s = soup.find_all( 'h3' )
    count = 0
    for h3 in h3s:
        # h3 is not a dict. Use the method provided by BeautifulSoup
        if not h3.has_attr( 'class' ):
            continue
        if str( h3[ 'class' ][ 0 ] ) == 'definition':
            count += 1
            text = h3.text
            # Sanitize the string
            text = str( text.replace( '\n', '' ).replace( '\r', '' ).replace( '\t', '' ) )
            # There are spaces between the part of speech and the definition
            firstSpace = text.find( ' ' )
            i = firstSpace
            while i < len( text ):
                if text[ i ] != ' ':
                    definition = text[ i: ]
                    break
                i += 1
            print '(' + str( count ) + ') ' + str( h3.a.text ) + '. ' + definition

    # Either the spelling was incorrect, or vocabulary.com doesn't have such a word in
    # their dictionary, or our script has a bug! Warn the user about this
    if count == 0:
        print "Sorry! We could not find the definition of the word you provided."
        print
        print "Please check if the spelling of the word you provided is correct. " + \
               "If the spelling is correct, it is possible that the word is not present " + \
               "in vocabulary.com dictionary. If you feel that the word is present in the dictionary, " + \
               "please open an issue against this script at https://github.com/crisron/CoolScripts/issues"

if __name__ == '__main__':
    main()
